# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   # pull_request:
#   #   branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

name: ErgoSense with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (faster builds)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ergosense:ci .

      - name: Run container in background
        run: |
          docker run -d --name ergosense_test -p 8501:8501 ergosense:ci
          sleep 10  # wait for server to start

      - name: Smoke test container
        run: curl -f http://localhost:8501 || (docker logs ergosense_test && exit 1)

      - name: Clean up
        if: always()
        run: docker rm -f ergosense_test || true

